### ISSUE TITLE
Wrong path for fonts

### ISSUE THREAD

**Issue by michielgerritsen** [tightenco/jigsaw#233]
Hello,

Currently i'm trying to include Font Awesome in my project. I have added it to npm by running:
`npm i --save font-awesome`

And importing it into my css:
`@import '../../../node_modules/font-awesome/scss/font-awesome';`

This works pretty wel, except that the generated path for the fonts is incorrect. It is missing the `assets` part. When i inspect the generated css, this path is generated:
`/fonts/vendor/font-awesome/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713`

But it should be:
`/assets/fonts/vendor/font-awesome/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713`

For now i solved this by using the CDN variant of Font Awesome, but for other modules this is not always possible.

**Comment by damiani** [comment]
I believe setting the `$fa-font-path` should accomplish this:

```
$fa-font-path: '/assets/fonts/vendor/font-awesome';
@import '~font-awesome/scss/font-awesome';
```

In my testing, this renders:

```css
@font-face {
  font-family: 'FontAwesome';
  src: url("/assets/fonts/vendor/font-awesome/fontawesome-webfont.eot?v=4.7.0");
  src: url("/assets/fonts/vendor/font-awesome/fontawesome-webfont.eot?#iefix&v=4.7.0") format("embedded-opentype"), url("/assets/fonts/vendor/font-awesome/fontawesome-webfont.woff2?v=4.7.0") format("woff2"), url("/assets/fonts/vendor/font-awesome/fontawesome-webfont.woff?v=4.7.0") format("woff"), url("/assets/fonts/vendor/font-awesome/fontawesome-webfont.ttf?v=4.7.0") format("truetype"), url("/assets/fonts/vendor/font-awesome/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```
