### ISSUE TITLE
Sorting by nested field

### ISSUE THREAD

**Issue by wing5wong** [tightenco/jigsaw#372]
Tried to search on this but came up with nothing.

Given the following front matter, we would like to display a paginated collection of news articles that is sorted by `publication_detail.date`

is this possible? can i define a custom sort function to be used in a paginated collection.

``` yml
---
title: Random title
date: 2019-09-03T03:57:49.697Z
# ...
publication_detail:
  date: 2019-09-02T22:46:41.627Z
  name: The author
  publication: The publication
---
```

``` php
// news layout
---
pagination:
    collection: news
    perPage: 15
---
@extends('_layouts.standard')
@section('title', "News")
@section('content')
// ...
```
